# Generated by Django 4.2.10 on 2026-03-03 19:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('reservation_number', models.CharField(max_length=50, unique=True)),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(blank=True, max_length=200)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('reservation_type', models.CharField(choices=[('HOST', 'Hébergement'), ('ACTIVITY', 'Activité'), ('COMBO', 'Combiné')], max_length=20)),
                ('host_id', models.IntegerField(blank=True, null=True)),
                ('host_name', models.CharField(blank=True, max_length=200)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('number_of_guests', models.IntegerField(default=1)),
                ('nights', models.IntegerField(default=0)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=200)),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('participants', models.IntegerField(default=1)),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20)),
                ('feedback_given', models.BooleanField(default=False)),
                ('feedback_id', models.IntegerField(blank=True, null=True)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reservations',
                'indexes': [models.Index(fields=['user_id'], name='reservation_user_id_94b298_idx'), models.Index(fields=['reservation_number'], name='reservation_reserva_d35c68_idx'), models.Index(fields=['status'], name='reservation_status_a87326_idx')],
            },
        ),
    ]
